config/routes.rb
Rails.application.routes.draw do
  root 'goals#show'

  resources :goals, only: [:new, :show, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/goal.rb
class Goal < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  def new
    @goal = Goal.new
  end

  def show
    @goals = Goal.all
  end

  def create
    @goal = Goal.create(goal_params)
    redirect_to root_path
  end

  private

  def goal_params
    params.require(:goal).permit(:title, :description)
  end

end

app/controllers/quiz_controller.rb
class QuizController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/quiz_helper.rb
module QuizHelper
end

app/views/goals/new.html.erb
<br />
<div class="booyah-box col-8 offset-2">
<h1>New</h1>
<%= simple_form_for @goal, url: goals_path do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <br />
  <%= f.submit "Add goal", class: 'btn btn-primary' %>
  <br />
<% end %>
</div>
<br />

app/views/goals/show.html.erb
<div class="booyah-box col-8 offset-2">
<h1>Goals</h1>
<ul>
  <% @goals.each do |goal| %>

    <li>
      <%= goal.title %> - <%= goal.description %>
    </li>

  <% end %>
</ul>


<%= link_to 'Add new goal', new_goal_path, class: 'btn btn-primary' %>
</div>
<br />

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quiz1</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar sticky-top navbar-toggleable-md navbar-inverse" style="background-color: #7e92b5">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <%= link_to 'Moop', root_path, class: 'navbar-brand' %>
  <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
    <ul class="navbar-nav mr-auto mt-2 mt-md-0">
      <li class="nav-item active">
        <a class="nav-link" href="#">About <span class="sr-only">(current)</span></a>
      </li>

    </ul>

  </div>
</nav>
    <%= yield %>
<nav class="navbar navbar-inverse" style="background-color: #394251">
  <%= link_to 'Moop', root_path, class: 'navbar-brand' %>
</nav>
  </body>
</html>

app/views/quiz/index.html.erb
<br />
<div>
  <h1>Boo</h1>
</div>